name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install all dependencies
        run: pnpm install

      - name: Generates the icons components
        run: pnpm generate:icons

      - name: Run Prettier format
        run: pnpm format

      - name: Run Lint
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm lint

      - name: Build the package
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm build

      - name: Run postbuild scripts
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm postbuild

      - name: Publish to NPM Packages
        run: HUSKY=0 npm publish --access public ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@indaco'

      - name: Publish to GitHub Packages
        run: HUSKY=0 npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
